-- Add remaining categories: PCOD-Friendly, Pregnancy Support, Microgreen-Based

-- PCOD-Friendly Category  
INSERT INTO products (name, dish_name, description, category, subcategory, veg_or_nonveg, dressing, crunch_topping, price, macros, tags, recipe_link, image_url, image_opened_url, is_enabled) VALUES
('Cinnamon Quinoa Balance', 'Cinnamon Quinoa Balance', 'Quinoa with a touch of cinnamon, known to help with insulin sensitivity, combined with balancing ingredients.', 'Salads', 'PCOD-Friendly', 'Veg', 'Light Cinnamon-Apple Vinaigrette', 'Toasted Walnuts', 319, '{"calories": 340, "protein": 10, "carbs": 45, "fat": 14, "sugar": 8}', 'v, gf, pc', 'Coming Soon!', 'https://i.postimg.cc/wTj0NTK9/55-Nutrient-Dense-Delight.png', 'https://i.postimg.cc/K8ChNPWN/41-CINNAMON-AND-QUINOA-BALANCE.png', true),
('Flax & Berry Harmony', 'Flax & Berry Harmony', 'A blend of berries and flax seeds, rich in antioxidants and omega-3s, beneficial for hormonal balance.', 'Salads', 'PCOD-Friendly', 'Veg', 'Berry Chia Seed Dressing', 'Ground Flax Seeds', 299, '{"calories": 280, "protein": 6, "carbs": 38, "fat": 10, "sugar": 12}', 'v, gf, pc', 'Coming Soon!', 'https://i.postimg.cc/PxHM5dzs/56-Spinach-Lentil-Power.png', 'https://i.postimg.cc/3wp5by5H/42-FLAX-AND-BERRY-HARMONY.png', true),
('Chickpea & Amla Detox', 'Chickpea & Amla Detox', 'Protein-rich chickpeas with amla, supporting detoxification and hormonal health.', 'Salads', 'PCOD-Friendly', 'Veg', 'Lemon-Coriander Dressing', 'Roasted Cumin Seeds', 299, '{"calories": 310, "protein": 15, "carbs": 35, "fat": 10, "sugar": 6}', 'v, gf, hp, pc', 'Coming Soon!', 'https://i.postimg.cc/4yPdTNhx/57-Microgreen-Superfood-Bowl.png', 'https://i.postimg.cc/3wp5by5H/42-FLAX-AND-BERRY-HARMONY.png', true),
('Moringa & Lentil Support', 'Moringa & Lentil Support', 'Moringa leaves combined with lentils, providing essential nutrients for hormonal balance.', 'Salads', 'PCOD-Friendly', 'Veg', 'Tahini-Lemon Dressing', 'Sesame Seeds', 309, '{"calories": 320, "protein": 18, "carbs": 32, "fat": 12, "sugar": 5}', 'v, gf, hp, pc', 'Coming Soon!', 'https://i.postimg.cc/J054ZVFk/70-Grape-Walnut-Crunch.png', 'https://i.postimg.cc/8zhDrHg8/44-Moringa-Lentil-Support.png', true),
('Avocado & Seed Balance', 'Avocado & Seed Balance', 'Creamy avocado with a mix of seeds, providing healthy fats essential for hormone production.', 'Salads', 'PCOD-Friendly', 'Veg', 'Lime-Cilantro Dressing', 'Mixed Seeds', 329, '{"calories": 380, "protein": 12, "carbs": 25, "fat": 25, "sugar": 4}', 'v, gf, pc', 'Coming Soon!', 'https://i.postimg.cc/TYTPG1yq/71-Kiwi-Spinach-Detox.png', 'https://i.postimg.cc/3w1Ttxwn/45-Avocado-Seed-Balance.png', true),
('Grilled Chicken & Greens', 'Grilled Chicken & Greens', 'Lean protein from grilled chicken with leafy greens, supporting metabolism and insulin sensitivity.', 'Salads', 'PCOD-Friendly', 'Non-Veg', 'Herb Vinaigrette', 'Pumpkin Seeds', 399, '{"calories": 370, "protein": 32, "carbs": 18, "fat": 18, "sugar": 3}', 'hp, gf, pc', 'Coming Soon!', 'https://i.postimg.cc/NG60Wm0j/72-Power-Berry-Banana.png', 'https://i.postimg.cc/2yBgNkzp/46-Grilled-Chicken-Greens.png', true),
('Spinach & Paneer Delight', 'Spinach & Paneer Delight', 'Iron-rich spinach with protein-packed paneer, supporting overall health and hormonal balance.', 'Salads', 'PCOD-Friendly', 'Veg', 'Yogurt-Mint Dressing', 'Roasted Cashews', 349, '{"calories": 360, "protein": 22, "carbs": 20, "fat": 20, "sugar": 6}', 'v, gf, hp, pc', 'Coming Soon!', 'https://i.postimg.cc/fRLTtPfV/73-Cardamom-Fig-Overnight-Oats.png', 'https://i.postimg.cc/NMnZn9v7/47-Spinach-Paneer-Delight.png', true),
('Broccoli & Quinoa Boost', 'Broccoli & Quinoa Boost', 'Nutrient-dense broccoli with quinoa, providing fiber and essential vitamins for PCOD management.', 'Salads', 'PCOD-Friendly', 'Veg', 'Lemon-Herb Dressing', 'Sunflower Seeds', 299, '{"calories": 300, "protein": 14, "carbs": 38, "fat": 10, "sugar": 4}', 'v, gf, pc', 'Coming Soon!', 'https://i.postimg.cc/mgtB2HTM/74-Tropical-Coconut-Overnight-Oats.png', 'https://i.postimg.cc/637BTN9c/48-Broccoli-Quinoa-Boost.png', true);

-- Pregnancy Support Category
INSERT INTO products (name, dish_name, description, category, subcategory, veg_or_nonveg, dressing, crunch_topping, price, macros, tags, recipe_link, image_url, image_opened_url, is_enabled) VALUES
('Folic Acid Power Bowl', 'Folic Acid Power Bowl', 'Rich in folate from leafy greens and legumes, essential for fetal development and maternal health.', 'Salads', 'Pregnancy Support', 'Veg', 'Lemon-Tahini Dressing', 'Toasted Pine Nuts', 349, '{"calories": 340, "protein": 16, "carbs": 30, "fat": 18, "sugar": 5}', 'v, gf, hp, pg', 'Coming Soon!', 'https://i.postimg.cc/pTtHZczY/75-Berry-Blast-Overnight-Oats.png', 'https://i.postimg.cc/KvhmcVC7/49-Folic-Acid-Power-Bowl.png', true),
('Calcium & Iron Rich', 'Calcium & Iron Rich', 'Packed with calcium from paneer/tofu and iron from spinach, vital for maternal and fetal health.', 'Salads', 'Pregnancy Support', 'Veg', 'Light Yogurt-Dill Dressing', 'Sesame Seeds', 349, '{"calories": 350, "protein": 20, "carbs": 25, "fat": 18, "sugar": 4}', 'v, hp, gf, pg', 'Coming Soon!', 'https://i.postimg.cc/QC2Cjd1c/63-Mediterranean-Microgreen.png', 'https://i.postimg.cc/QCh6mCsS/5-SMOKED-SALMON-AND-AVOCADO.png', true),
('Omega-3 Berry Blend', 'Omega-3 Berry Blend', 'A delicious source of omega-3 fatty acids from chia seeds and berries, supporting brain development.', 'Salads', 'Pregnancy Support', 'Veg', 'Berry Chia Seed Dressing', 'Chia Seeds', 299, '{"calories": 290, "protein": 6, "carbs": 38, "fat": 12, "sugar": 12}', 'v, gf, pg', 'Coming Soon!', 'https://i.postimg.cc/yYRWv0Cj/64-Spicy-Prawn-Microgreen.png', 'https://i.postimg.cc/D00xHDJb/50-CLACIUM-AND-IRON-RICH.png', true),
('Hydration & Fiber Fresco', 'Hydration & Fiber Fresco', 'High water content fruits and fiber-rich ingredients to aid digestion and hydration during pregnancy.', 'Salads', 'Pregnancy Support', 'Veg', 'Fresh Mint-Lime Dressing', 'Toasted Coconut Flakes', 279, '{"calories": 260, "protein": 4, "carbs": 35, "fat": 8, "sugar": 15}', 'v, gf, pg', 'Coming Soon!', 'https://i.postimg.cc/85szW6bh/65-Tropical-Sunrise-Fruit-Bowl.png', 'https://i.postimg.cc/fT68q8wJ/51-OMEGA-3-BERRY-BLEND.png', true),
('Protein & Fiber Boost', 'Protein & Fiber Boost', 'A balanced salad with lean protein and ample fiber for sustained energy and digestive comfort. Available with Chickpeas for veg option.', 'Salads', 'Pregnancy Support', 'Non-Veg', 'Balsamic Vinaigrette', 'Roasted Pumpkin Seeds', 399, '{"calories": 380, "protein": 28, "carbs": 35, "fat": 18, "sugar": 6}', 'hp, gf, pg', 'Coming Soon!', 'https://i.postimg.cc/DZWXrZQb/66-Berry-Burst-Fruit-Salad.png', 'https://i.postimg.cc/VknDxX64/52-HYDRATION-AND-FIBER-FRESCO.png', true),
('Ginger & Carrot Glow', 'Ginger & Carrot Glow', 'Ginger for nausea relief and carrots for Vitamin A, supporting overall maternal wellness.', 'Salads', 'Pregnancy Support', 'Veg', 'Orange-Ginger Vinaigrette', 'Sliced Almonds', 289, '{"calories": 270, "protein": 4, "carbs": 30, "fat": 12, "sugar": 10}', 'v, gf, pg', 'Coming Soon!', 'https://i.postimg.cc/sXtZwrKH/67-Fig-Date-Delight.png', 'https://i.postimg.cc/nL1TzZqD/53-PROTEIN-AND-FIBER-BOOST.png', true),
('Nutrient-Dense Delight', 'Nutrient-Dense Delight', 'A comprehensive salad providing a wide array of vitamins and minerals essential for pregnancy. Available with Grilled Chicken for non-veg option.', 'Salads', 'Pregnancy Support', 'Veg', 'Honey-Mustard Vinaigrette', 'Mixed Roasted Nuts', 369, '{"calories": 390, "protein": 18, "carbs": 35, "fat": 22, "sugar": 9}', 'v, hp, gf, pg', 'Coming Soon!', 'https://i.postimg.cc/RhKJYDDS/68-Mediterranean-Fruit-Medley.png', 'https://i.postimg.cc/85KHRHKk/54-GINGER-CARROT-GLOW.png', true),
('Spinach & Lentil Power', 'Spinach & Lentil Power', 'A hearty salad combining iron-rich spinach with protein-packed lentils, vital for energy and blood count.', 'Salads', 'Pregnancy Support', 'Veg', 'Lemon-Tahini Dressing', 'Crispy Garlic Bits', 309, '{"calories": 310, "protein": 16, "carbs": 30, "fat": 12, "sugar": 5}', 'v, gf, hp, pg', 'Coming Soon!', 'https://i.postimg.cc/sDChW3Mv/69-Spicy-Guava-Pomegranate.png', 'https://i.postimg.cc/6q8hYvgr/55-NUTRIENT-DENSE-DELIGHT.png', true);