-- Add final categories: Microgreen-Based, Fruit Salads, Extras

-- Microgreen-Based Category
INSERT INTO products (name, dish_name, description, category, subcategory, veg_or_nonveg, dressing, crunch_topping, price, macros, tags, recipe_link, image_url, image_opened_url, is_enabled) VALUES
('Microgreen Superfood Bowl', 'Microgreen Superfood Bowl', 'A vibrant salad showcasing the intense nutrients of mixed microgreens with a light, refreshing base.', 'Salads', 'Microgreen-Based', 'Veg', 'Lemon-Herb Vinaigrette', 'Toasted Pine Nuts', 349, '{"calories": 300, "protein": 8, "carbs": 20, "fat": 20, "sugar": 4}', 'v, gf, mg', 'Coming Soon!', 'https://i.postimg.cc/Gp2Yp96y/7-SPROUTS-AND-SEED-POWER.png', 'https://i.postimg.cc/Pf7yNSv2/56-SPINACH-AND-LENTIL-POWER.png', true),
('Sprouted Lentil & Microgreen', 'Sprouted Lentil & Microgreen', 'Protein-packed sprouted lentils combined with fresh microgreens for a nutrient-dense meal.', 'Salads', 'Microgreen-Based', 'Veg', 'Cumin-Lime Dressing', 'Roasted Cumin Seeds', 329, '{"calories": 310, "protein": 16, "carbs": 30, "fat": 10, "sugar": 5}', 'v, gf, hp, mg', 'Coming Soon!', 'https://i.postimg.cc/J054ZVFk/70-Grape-Walnut-Crunch.png', 'https://i.postimg.cc/FH5xV1ZS/57-MICROGREEN-SUPERFOOD-BOWL.png', true),
('Quinoa & Microgreen Medley', 'Quinoa & Microgreen Medley', 'Wholesome quinoa mixed with a generous serving of microgreens, offering a complete and balanced meal.', 'Salads', 'Microgreen-Based', 'Veg', 'Balsamic Glaze', 'Toasted Almond Slivers', 339, '{"calories": 350, "protein": 12, "carbs": 45, "fat": 15, "sugar": 8}', 'v, gf, mg', 'Coming Soon!', 'https://i.postimg.cc/TYTPG1yq/71-Kiwi-Spinach-Detox.png', 'https://i.postimg.cc/9MndRf0r/58-SPROUTED-LENTIL-AND-MICROGREEN.png', true),
('Grilled Chicken & Microgreens', 'Grilled Chicken & Microgreens', 'Lean grilled chicken breast paired with a fresh bed of microgreens for a light yet satisfying protein boost.', 'Salads', 'Microgreen-Based', 'Non-Veg', 'Light Lemon-Herb Dressing', 'Crispy Garlic Bits', 419, '{"calories": 380, "protein": 30, "carbs": 15, "fat": 20, "sugar": 3}', 'hp, gf, mg', 'Coming Soon!', 'https://i.postimg.cc/NG60Wm0j/72-Power-Berry-Banana.png', 'https://i.postimg.cc/0jKppqKZ/59-QUINOA-AND-MICROGREEN-MEDLEY.png', true),
('Beetroot & Microgreen Fusion', 'Beetroot & Microgreen Fusion', 'Earthy beetroot and vibrant microgreens create a visually stunning and nutrient-rich salad.', 'Salads', 'Microgreen-Based', 'Veg', 'Orange-Ginger Vinaigrette', 'Roasted Pumpkin Seeds', 319, '{"calories": 320, "protein": 8, "carbs": 35, "fat": 18, "sugar": 9}', 'v, gf, mg', 'Coming Soon!', 'https://i.postimg.cc/fRLTtPfV/73-Cardamom-Fig-Overnight-Oats.png', 'https://i.postimg.cc/R0tXzKZX/6-LENTIL-FETA-MEDLEY.png', true),
('Tofu & Microgreen Zen', 'Tofu & Microgreen Zen', 'Pan-seared tofu with a calming blend of microgreens, offering a plant-based protein option.', 'Salads', 'Microgreen-Based', 'Veg', 'Soy-Ginger Vinaigrette', 'Toasted Sesame Seeds', 339, '{"calories": 340, "protein": 20, "carbs": 25, "fat": 18, "sugar": 5}', 'v, df, hp, mg', 'Coming Soon!', 'https://i.postimg.cc/mgtB2HTM/74-Tropical-Coconut-Overnight-Oats.png', 'https://i.postimg.cc/RCW8P6cp/60-GRILLED-CHICKEN-AND-MICROGREENS.png', true),
('Mediterranean Microgreen', 'Mediterranean Microgreen', 'A fresh take on Mediterranean flavors, with microgreens adding an extra layer of nutrition.', 'Salads', 'Microgreen-Based', 'Veg', 'Lemon-Tahini Dressing', 'Toasted Pine Nuts', 349, '{"calories": 360, "protein": 15, "carbs": 30, "fat": 20, "sugar": 6}', 'v, gf, mg', 'Coming Soon!', 'https://i.postimg.cc/pTtHZczY/75-Berry-Blast-Overnight-Oats.png', 'https://i.postimg.cc/Z0k6HDrm/61-BEETROOT-AND-MICROGREEN-FUSION.png', true),
('Spicy Prawn & Microgreen', 'Spicy Prawn & Microgreen', 'Succulent prawns with a kick of spice, balanced by the freshness of microgreens.', 'Salads', 'Microgreen-Based', 'Non-Veg', 'Chilli-Lime Dressing', 'Crispy Fried Shallots', 429, '{"calories": 400, "protein": 32, "carbs": 18, "fat": 22, "sugar": 4}', 'hp, gf, mg', 'Coming Soon!', 'https://i.postimg.cc/YqSwbWGV/76-Peanut-Butter-Power-Oats.png', 'https://i.postimg.cc/c4YzSpkQ/62-TOFU-AND-MICROGREEN-ZEN.png', true);

-- Fruit Salads Category
INSERT INTO products (name, dish_name, description, category, subcategory, veg_or_nonveg, dressing, crunch_topping, price, macros, tags, recipe_link, image_url, image_opened_url, is_enabled) VALUES
('Tropical Sunrise Fruit Bowl', 'Tropical Sunrise Fruit Bowl', 'A vibrant mix of seasonal tropical fruits, light and refreshing, perfect for a healthy start or mid-day energizer.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Honey-Lime Mint Drizzle', 'Toasted Coconut Chips', 279, '{"calories": 280, "protein": 4, "carbs": 65, "fat": 5, "sugar": 35}', 'v, gf, df, wl', 'Coming Soon!', 'https://i.postimg.cc/zvxYqJM0/77-Apple-Cinnamon-Overnight-Oats.png', 'https://i.postimg.cc/bwhBNm44/63-MEDITERRANEAN-MICROGREEN.png', true),
('Berry Burst Fruit Salad', 'Berry Burst Fruit Salad', 'An antioxidant-rich blend of mixed berries with a hint of citrus, promoting vitality and freshness.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Orange-Ginger Vinaigrette', 'Toasted Almond Slivers', 289, '{"calories": 260, "protein": 3, "carbs": 60, "fat": 4, "sugar": 30}', 'v, gf, df, wl', 'Coming Soon!', 'https://i.postimg.cc/g0FQFXjG/78-Moong-Dal-Overnight-Oats-Savory.png', 'https://i.postimg.cc/g0ct3nzD/64-SPICY-PRAWN-AND-MICROGREEN.png', true),
('Fig & Date Delight', 'Fig & Date Delight', 'Sweet and earthy flavors of fresh figs and dates, balanced with crisp apple for a wholesome indulgence.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Cardamom Honey Drizzle', 'Crushed Pistachios', 309, '{"calories": 320, "protein": 6, "carbs": 70, "fat": 8, "sugar": 40}', 'v, gf', 'Coming Soon!', 'https://i.postimg.cc/85w06ZHC/79-Chocolate-Hazelnut-Overnight-Oats.png', 'https://i.postimg.cc/k5j1sqDd/65-TROPICAL-SUNRISE-FRUIT-BOWL.png', true),
('Mediterranean Fruit Medley', 'Mediterranean Fruit Medley', 'A refreshing fruit salad with a Mediterranean twist, featuring cooling cucumber and mint.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Lemon-Mint Infusion', 'Toasted Pine Nuts', 279, '{"calories": 250, "protein": 5, "carbs": 55, "fat": 7, "sugar": 28}', 'v, gf', 'Coming Soon!', 'https://i.postimg.cc/bvBnSpjF/8-Grilled-Halloumi-Berry.png', 'https://i.postimg.cc/G2VM0Kk7/66-BERRY-BURST-FRUIT-SALAD.png', true),
('Spicy Guava & Pomegranate', 'Spicy Guava & Pomegranate', 'A zesty and spicy fruit salad with popular Indian street food flavors for a unique kick.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Chilli-Lime-Chaat Masala Vinaigrette', 'Roasted Cumin Seeds', 269, '{"calories": 240, "protein": 4, "carbs": 58, "fat": 3, "sugar": 25}', 'v, gf, df, wl', 'Coming Soon!', 'https://i.postimg.cc/T1wHqn7J/80-Pistachio-Rose-Overnight-Oats.png', 'https://i.postimg.cc/tJ6B96kX/67-FIG-AND-DATE-DELIGHT.png', true),
('Grape & Walnut Crunch', 'Grape & Walnut Crunch', 'Sweet grapes and crunchy walnuts with a creamy base, a satisfying and healthy treat.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Light Yogurt-Dill Dressing', 'Toasted Walnuts', 289, '{"calories": 300, "protein": 7, "carbs": 50, "fat": 12, "sugar": 28}', 'v, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/WzHY9txL/81-Moringa-Magic-Smoothie-Bowl.png', 'https://i.postimg.cc/c4qDXD16/68-MEDITERRANEAN-FRUIT-MELDY.png', true),
('Kiwi & Spinach Detox', 'Kiwi & Spinach Detox', 'A refreshing combination of tart kiwi and fresh spinach for a cleansing and energizing fruit salad.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Lemon-Mint Dressing', 'Pumpkin Seeds', 259, '{"calories": 220, "protein": 5, "carbs": 45, "fat": 6, "sugar": 22}', 'v, gf, df, wl', 'Coming Soon!', 'https://i.postimg.cc/J054ZVFk/70-Grape-Walnut-Crunch.png', 'https://i.postimg.cc/TYTPG1yq/71-Kiwi-Spinach-Detox.png', true),
('Power Berry & Banana', 'Power Berry & Banana', 'An energizing fruit salad with antioxidant-rich berries and potassium-packed bananas.', 'Salads', 'Assorted Fruit Salad', 'Veg', 'Vanilla-Cinnamon Drizzle', 'Granola Clusters', 269, '{"calories": 290, "protein": 6, "carbs": 62, "fat": 8, "sugar": 32}', 'v, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/NG60Wm0j/72-Power-Berry-Banana.png', 'https://i.postimg.cc/NG60Wm0j/72-Power-Berry-Banana.png', true);