-- Add Weight Loss category items
INSERT INTO products (name, dish_name, description, category, subcategory, veg_or_nonveg, dressing, crunch_topping, price, macros, tags, recipe_link, image_url, image_opened_url, is_enabled) VALUES
('Lean Green Detox', 'Lean Green Detox', 'A cleansing and low-calorie salad packed with detoxifying greens and light protein.', 'Salads', 'Weight Loss', 'Veg', 'Apple Cider Vinaigrette', 'Crispy Kale Chips', 299, '{"calories": 280, "protein": 15, "carbs": 25, "fat": 12, "sugar": 7}', 'v, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/JhZy0JPt/31-Tofu-Mushroom-Medley.png', 'https://i.postimg.cc/dt8Cv627/27-QUINOA-AND-VEGGIE-POWER.png', true),
('Berry Blast Slim', 'Berry Blast Slim', 'A refreshing and antioxidant-rich salad with mixed berries, promoting satiety and aiding weight loss.', 'Salads', 'Weight Loss', 'Veg', 'Light Berry Vinaigrette', 'Goji Berries', 279, '{"calories": 250, "protein": 8, "carbs": 35, "fat": 7, "sugar": 10}', 'v, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/mDPQmhws/4-SPICED-CHICKPEA-AND-QUINOA.png', 'https://i.postimg.cc/fLt3PfWR/28-GRILLED-PRAWN-AND-CITRUS.png', true),
('Quinoa & Veggie Power', 'Quinoa & Veggie Power', 'A fiber-rich and filling salad with wholesome quinoa and a vibrant mix of colorful vegetables.', 'Salads', 'Weight Loss', 'Veg', 'Lemon-Herb Vinaigrette', 'Toasted Sunflower Seeds', 309, '{"calories": 320, "protein": 10, "carbs": 40, "fat": 10, "sugar": 6}', 'v, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/TYK3hgPG/42-Flax-Berry-Harmony.png', 'https://i.postimg.cc/B6r8fPtc/29-CABBAGE-CRUNCH-AND-CHICKEN.png', true),
('Grilled Prawn & Citrus', 'Grilled Prawn & Citrus', 'Lean grilled prawns with zesty citrus fruits, offering a low-calorie, high-protein, and refreshing option.', 'Salads', 'Weight Loss', 'Non-Veg', 'Orange-Ginger Vinaigrette', 'Sesame Seeds', 429, '{"calories": 350, "protein": 28, "carbs": 20, "fat": 15, "sugar": 8}', 'hp, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/02h2Sj6S/43-Chickpea-Amla-Detox.png', 'https://i.postimg.cc/9M3g41n6/3-TOFU-AND-EDAMEME-ZING.png', true),
('Cabbage Crunch & Chicken', 'Cabbage Crunch & Chicken', 'A satisfyingly crunchy salad with shredded cabbage and lean grilled chicken, low in calories but high in flavor.', 'Salads', 'Weight Loss', 'Non-Veg', 'Light Peanut Dressing', 'Crushed Roasted Peanuts', 399, '{"calories": 360, "protein": 30, "carbs": 20, "fat": 18, "sugar": 4}', 'hp, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/8zhDrHg8/44-Moringa-Lentil-Support.png', 'https://i.postimg.cc/P5XCHjfc/30-WATERMELON-AND-FETO-FRESCO.png', true),
('Watermelon & Feta Fresco', 'Watermelon & Feta Fresco', 'A classic refreshing salad that is hydrating and low in calories, perfect for light meals.', 'Salads', 'Weight Loss', 'Veg', 'Balsamic Glaze', 'Fresh Mint Leaves', 269, '{"calories": 260, "protein": 8, "carbs": 30, "fat": 10, "sugar": 12}', 'v, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/3w1Ttxwn/45-Avocado-Seed-Balance.png', 'https://i.postimg.cc/15c8btSw/31-TOFU-AND-MUSHROOM-MEDLEY.png', true),
('Tofu & Mushroom Medley', 'Tofu & Mushroom Medley', 'A light and flavorful plant-based salad with protein-rich tofu and earthy mushrooms.', 'Salads', 'Weight Loss', 'Veg', 'Soy-Ginger Vinaigrette', 'Crispy Garlic Bits', 319, '{"calories": 300, "protein": 18, "carbs": 25, "fat": 15, "sugar": 5}', 'v, df, hp, wl', 'Coming Soon!', 'https://i.postimg.cc/2yBgNkzp/46-Grilled-Chicken-Greens.png', 'https://i.postimg.cc/Hn0LGSqd/32-GARDEN-HARVEST-WITH-SEEDS.png', true),
('Garden Harvest with Seeds', 'Garden Harvest with Seeds', 'A simple, fresh garden salad enhanced with a mix of seeds for added nutrients and satiety.', 'Salads', 'Weight Loss', 'Veg', 'Lemon-Herb Vinaigrette', 'Mixed Roasted Seeds', 249, '{"calories": 270, "protein": 8, "carbs": 25, "fat": 15, "sugar": 4}', 'v, gf, wl', 'Coming Soon!', 'https://i.postimg.cc/NMnZn9v7/47-Spinach-Paneer-Delight.png', 'https://i.postimg.cc/8PD5dSv5/33-CITRUS-AMLA-BOOST.png', true);