-- Add remaining categories: Vitamin Deficiency, PCOD-Friendly, Pregnancy Support, Microgreen-Based, Fruit Salads, Overnight Oats, Smoothie Bowls, Smoothies, and Extras

-- Vitamin Deficiency Category
INSERT INTO products (name, dish_name, description, category, subcategory, veg_or_nonveg, dressing, crunch_topping, price, macros, tags, recipe_link, image_url, image_opened_url, is_enabled) VALUES
('Citrus Amla Boost', 'Citrus Amla Boost', 'A powerful vitamin C rich salad with citrus fruits and Indian gooseberry (Amla) for immunity.', 'Salads', 'Vitamin Deficiency', 'Veg', 'Honey-Lime Vinaigrette', 'Toasted Almonds', 319, '{"calories": 290, "protein": 5, "carbs": 40, "fat": 10, "sugar": 18}', 'v, gf', 'Coming Soon!', 'https://i.postimg.cc/637BTN9c/48-Broccoli-Quinoa-Boost.png', 'https://i.postimg.cc/c171LbzN/34-KALE-AND-BERRY.png', true),
('Kale & Berry Iron Rich', 'Kale & Berry Iron Rich', 'A vibrant salad packed with iron-rich kale and berries, essential for combating iron deficiency.', 'Salads', 'Vitamin Deficiency', 'Veg', 'Balsamic Vinaigrette', 'Dried Cranberries', 309, '{"calories": 300, "protein": 6, "carbs": 45, "fat": 10, "sugar": 15}', 'v, gf', 'Coming Soon!', 'https://i.postimg.cc/KvhmcVC7/49-Folic-Acid-Power-Bowl.png', 'https://i.postimg.cc/GtRcjFHN/35-SUNSHINE-VITAMIN-D.png', true),
('Sunshine Vitamin D Salad', 'Sunshine Vitamin D Salad', 'A unique salad with ingredients known to support Vitamin D synthesis and absorption. Available with Tofu for a veg option.', 'Salads', 'Vitamin Deficiency', 'Non-Veg', 'Creamy Mushroom Dressing', 'Sun-Dried Tomato Bits', 399, '{"calories": 390, "protein": 25, "carbs": 20, "fat": 22, "sugar": 5}', 'hp, gf', 'Coming Soon!', 'https://i.postimg.cc/0yCdQTQL/5-SMOKED-SALMON-AND-AVOCADO.png', 'https://i.postimg.cc/Qx0XpWs4/36-CARROT-AND-TURMERIC-GLOW.png', true),
('Carrot & Turmeric Glow', 'Carrot & Turmeric Glow', 'A beta-carotene rich salad with fresh turmeric, promoting skin health and overall vitality.', 'Salads', 'Vitamin Deficiency', 'Veg', 'Orange-Turmeric Vinaigrette', 'Toasted Pumpkin Seeds', 299, '{"calories": 280, "protein": 4, "carbs": 38, "fat": 12, "sugar": 10}', 'v, gf', 'Coming Soon!', 'https://i.postimg.cc/135hfZBF/50-Calcium-Iron-Rich.png', 'https://i.postimg.cc/zGQ8QZyT/37-BROCCOLI-AND-BELL-PEPPER.png', true),
('Broccoli & Bell Pepper C', 'Broccoli & Bell Pepper C', 'A potent dose of Vitamin C from broccoli and colorful bell peppers, supporting immune function.', 'Salads', 'Vitamin Deficiency', 'Veg', 'Lemon-Garlic Vinaigrette', 'Roasted Cashew Crumble', 289, '{"calories": 270, "protein": 6, "carbs": 28, "fat": 15, "sugar": 5}', 'v, gf', 'Coming Soon!', 'https://i.postimg.cc/HkZGMPvh/51-Omega-3-Berry-Blend.png', 'https://i.postimg.cc/sD6rBd9b/38-AVOCADOS-AND-GREENS.png', true),
('Avocado & Greens K', 'Avocado & Greens K', 'A rich source of Vitamin K from leafy greens and healthy fats from avocado, supporting bone health.', 'Salads', 'Vitamin Deficiency', 'Veg', 'Green Goddess Dressing', 'Pistachio Crumble', 349, '{"calories": 380, "protein": 8, "carbs": 20, "fat": 30, "sugar": 6}', 'v, gf, kf', 'Coming Soon!', 'https://i.postimg.cc/K8sVj3RX/52-Hydration-Fiber-Fresco.png', 'https://i.postimg.cc/WzSP6QRF/39-NUTRIENT-BURST.png', true),
('Nutrient Burst Salad', 'Nutrient Burst Salad', 'A comprehensive blend of ingredients providing a wide spectrum of essential vitamins and minerals.', 'Salads', 'Vitamin Deficiency', 'Veg', 'Balsamic-Herb Vinaigrette', 'Mixed Roasted Seeds', 329, '{"calories": 350, "protein": 15, "carbs": 40, "fat": 15, "sugar": 7}', 'v, gf, hp', 'Coming Soon!', 'https://i.postimg.cc/zfbQgDgy/53-Protein-Fiber-Boost.png', 'https://i.postimg.cc/Qtp4c1LH/4-SPICED-CHICKPEA-AND-QUINOA.png', true),
('Spinach & Egg B-Complex', 'Spinach & Egg B-Complex', 'A powerhouse of B vitamins from spinach and eggs, crucial for energy metabolism.', 'Salads', 'Vitamin Deficiency', 'Non-Veg', 'Light Yogurt-Dill Dressing', 'Crispy Chickpea Croutons', 319, '{"calories": 330, "protein": 20, "carbs": 15, "fat": 20, "sugar": 3}', 'hp, gf', 'Coming Soon!', 'https://i.postimg.cc/HnBzNFMG/54-Ginger-Carrot-Glow.png', 'https://i.postimg.cc/JzsWZ6p0/40-SPINACH-AND-EGG-B-COMPLEX.png', true);